USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE DAY3;
USE SCHEMA RAW;

ALTER WAREHOUSE COMPUTE_WH SET WAREHOUSE_SIZE='X-SMALL';

ALTER WAREHOUSE COMPUTE_WH RESUME;

--Make sure query results cache is not used
ALTER SESSION SET USE_CACHED_RESULT = FALSE;

/*
Create a copy of the table with 1.5B records with random order and no cluster
*/

create or replace TABLE DAY3.RAW.ORDERS_CLUSTERING_DEMO_NO_NATURAL_ORDER (
	O_ORDERKEY NUMBER(38,0),
	O_CUSTKEY NUMBER(38,0),
	O_ORDERSTATUS VARCHAR(1),
	O_TOTALPRICE NUMBER(12,2),
	O_ORDERDATE DATE,
	O_ORDERPRIORITY VARCHAR(15),
	O_CLERK VARCHAR(15),
	O_SHIPPRIORITY NUMBER(38,0),
	O_COMMENT VARCHAR(79)
);


INSERT INTO DAY3.RAW.ORDERS_CLUSTERING_DEMO_NO_NATURAL_ORDER 
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS
ORDER BY RANDOM(); --1m 20s -- 1 credit

--
SELECT COUNT(1) FROM DAY3.RAW.ORDERS_CLUSTERING_DEMO_NO_NATURAL_ORDER;


SELECT * FROM ORDERS_CLUSTERING_DEMO_NO_NATURAL_ORDER WHERE O_ORDERDATE='1997-09-19'; --42 SECONDS, FULL TABLE SCANE


/*
Create a copy of the table with 1.5B records a  cluster

*/

create or replace TABLE DAY3.RAW.ORDERS_CLUSTERING_DEMO_WITH_CLUSTER (
	O_ORDERKEY NUMBER(38,0),
	O_CUSTKEY NUMBER(38,0),
	O_ORDERSTATUS VARCHAR(1),
	O_TOTALPRICE NUMBER(12,2),
	O_ORDERDATE DATE,
	O_ORDERPRIORITY VARCHAR(15),
	O_CLERK VARCHAR(15),
	O_SHIPPRIORITY NUMBER(38,0),
	O_COMMENT VARCHAR(79)
) CLUSTER BY (O_ORDERDATE);--WHERE, JOIN, 



INSERT INTO DAY3.RAW.ORDERS_CLUSTERING_DEMO_WITH_CLUSTER 
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS;


SELECT * FROM DAY3.RAW.ORDERS_CLUSTERING_DEMO_WITH_CLUSTER WHERE O_ORDERDATE='1997-09-19';

--Use this function to check the clustering information.

SELECT SYSTEM$CLUSTERING_INFORMATION('ORDERS_CLUSTERING_DEMO_WITH_CLUSTER','O_ORDERDATE');
