USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_FUNDAMENTALS;
USE SCHEMA DAY3;

ALTER WAREHOUSE COMPUTE_WH SUSPEND;

--AUTO SUSPEND -- 1 HOUR (8 CREDIT 30 POUNDS)


--Reduce the size of the warehouse
ALTER WAREHOUSE COMPUTE_WH SET WAREHOUSE_SIZE='X-SMALL';

-- Alter session to not use the results cache
ALTER SESSION SET USE_CACHED_RESULT = FALSE;


--XS
SELECT
C_CUSTKEY,
SUM(O_TOTALPRICE) TOTAL_SALES,
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS O
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER C  ON O.O_CUSTKEY=C.C_CUSTKEY
GROUP BY C_CUSTKEY ; --XS 1min 28 


--Reduce the size of the warehouse
ALTER WAREHOUSE COMPUTE_WH SET WAREHOUSE_SIZE='MEDIUM';

--MEDIUM
SELECT
C_CUSTKEY,
SUM(O_TOTALPRICE) TOTAL_SALES,
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS O
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER C ON O.O_CUSTKEY=C.C_CUSTKEY
GROUP BY C_CUSTKEY ; 

--XS 1 min 28 sec
--S 1 min 5 sec
--Large 9.9 seconds
--Medium 23 s





EXPLAIN USING TABULAR
SELECT
C_CUSTKEY,
SUM(O_TOTALPRICE) TOTAL_SALES,
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS O
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER C  ON O.O_CUSTKEY=C.C_CUSTKEY
GROUP BY C_CUSTKEY ;


--01bc8065-0001-dd48-0002-5baa0005d526

select * from snowflake.account_usage.query_history limit 10;
